//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public long ID { get; set; }
        public string TextData { get; set; }
        public string TextData2 { get; set; }
        public Nullable<long> ParagraphID { get; set; }
        public Nullable<long> DocID { get; set; }
        public Nullable<long> Part { get; set; }
        public Nullable<long> PageFrom { get; set; }
        public Nullable<long> PageTo { get; set; }
        public Nullable<long> MainPageId { get; set; }
        public string IsHamesh { get; set; }
        public Nullable<long> treeId { get; set; }
        public string TextData_html { get; set; }
        public string TextData2_html { get; set; }
        public string SubjectLinks { get; set; }
        public string GegLinks { get; set; }
    }
}
